create table if not exists news (
    id bigint generated by default as identity primary key,
    title text not null,
    detail text,
    image_url text,
    created_at timestamptz default now()
);

create table if not exists complaint (
    id bigint generated by default as identity primary key,
    title text not null,
    detail text,
    image_url text,
    created_at timestamptz default now()
);

create table if not exists elderly (
    id bigint generated by default as identity primary key,
    title text not null,
    detail text,
    image_url text,
    created_at timestamptz default now()
);

create table if not exists vulnerable (
    id bigint generated by default as identity primary key,
    title text not null,
    detail text,
    image_url text,
    created_at timestamptz default now()
);

create table if not exists project (
    id bigint generated by default as identity primary key,
    title text not null,
    detail text,
    image_url text,
    created_at timestamptz default now()
);

create table if not exists incident (
    id bigint generated by default as identity primary key,
    title text not null,
    detail text,
    image_url text,
    created_at timestamptz default now()
);

create table if not exists activity (
    id bigint generated by default as identity primary key,
    title text not null,
    detail text,
    image_url text,
    created_at timestamptz default now()
);


alter table news enable row level security;
alter table complaint enable row level security;
alter table elderly enable row level security;
alter table vulnerable enable row level security;
alter table project enable row level security;
alter table incident enable row level security;
alter table activity enable row level security;


-- ทุกคนอ่านข้อมูลหน้าบ้านได้

create policy "news_select"
on news for select
using (true);

create policy "complaint_select"
on complaint for select
using (true);

create policy "elderly_select"
on elderly for select
using (true);

create policy "vulnerable_select"
on vulnerable for select
using (true);

create policy "project_select"
on project for select
using (true);

create policy "incident_select"
on incident for select
using (true);

create policy "activity_select"
on activity for select
using (true);


-- ผู้ที่ Login เพิ่มข้อมูล

create policy "news_insert"
on news for insert
to authenticated
with check (true);

create policy "complaint_insert"
on complaint for insert
to authenticated
with check (true);

create policy "elderly_insert"
on elderly for insert
to authenticated
with check (true);

create policy "vulnerable_insert"
on vulnerable for insert
to authenticated
with check (true);

create policy "project_insert"
on project for insert
to authenticated
with check (true);

create policy "incident_insert"
on incident for insert
to authenticated
with check (true);

create policy "activity_insert"
on activity for insert
to authenticated
with check (true);


-- ผู้ที่ Login แก้ไขและลบ

create policy "news_update"
on news for update
to authenticated
using (true)
with check (true);

create policy "news_delete"
on news for delete
to authenticated
using (true);


create policy "complaint_update"
on complaint for update
to authenticated
using (true)
with check (true);

create policy "complaint_delete"
on complaint for delete
to authenticated
using (true);


create policy "elderly_update"
on elderly for update
to authenticated
using (true)
with check (true);

create policy "elderly_delete"
on elderly for delete
to authenticated
using (true);


create policy "vulnerable_update"
on vulnerable for update
to authenticated
using (true)
with check (true);

create policy "vulnerable_delete"
on vulnerable for delete
to authenticated
using (true);


create policy "project_update"
on project for update
to authenticated
using (true)
with check (true);

create policy "project_delete"
on project for delete
to authenticated
using (true);


create policy "incident_update"
on incident for update
to authenticated
using (true)
with check (true);

create policy "incident_delete"
on incident for delete
to authenticated
using (true);


create policy "activity_update"
on activity for update
to authenticated
using (true)
with check (true);

create policy "activity_delete"
on activity for delete
to authenticated
using (true);


-- สร้าง Bucket เก็บรูป

insert into storage.buckets (
    id,
    name,
    public
)
values (
    'village-images',
    'village-images',
    true
)
on conflict (id) do nothing;


-- อ่านรูปได้

create policy "image_public_read"
on storage.objects
for select
using (
    bucket_id = 'village-images'
);


-- ผู้ Login อัปโหลดรูป

create policy "image_authenticated_insert"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'village-images'
);


create policy "image_authenticated_update"
on storage.objects
for update
to authenticated
using (
    bucket_id = 'village-images'
)
with check (
    bucket_id = 'village-images'
);


create policy "image_authenticated_delete"
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'village-images'
);
