/* =====================================================
   RONGKHEM e-VILLAGE OFFICE
   DATABASE
   AUTH + PROFILE + ROLE + RLS + AUDIT LOG
   ===================================================== */


/* =====================================================
   1. PROFILES
   ===================================================== */

create table if not exists public.profiles (

    id uuid
        primary key
        references auth.users(id)
        on delete cascade,

    username text
        unique
        not null,

    display_name text
        not null
        default 'ผู้ใหญ่บ้าน',

    role text
        not null
        default 'admin',

    active boolean
        not null
        default true,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint profiles_role_check
        check (
            role in (
                'admin',
                'leader',
                'staff',
                'viewer'
            )
        )

);


/* =====================================================
   2. AUDIT LOG
   ===================================================== */

create table if not exists public.audit_logs (

    id bigint
        generated by default as identity
        primary key,

    user_id uuid
        references auth.users(id)
        on delete set null,

    username text,

    action text
        not null,

    target text,

    details jsonb,

    created_at timestamptz
        not null
        default now()

);


/* =====================================================
   3. INDEX
   ===================================================== */

create index if not exists
idx_profiles_username

on public.profiles(username);


create index if not exists
idx_profiles_role

on public.profiles(role);


create index if not exists
idx_profiles_active

on public.profiles(active);


create index if not exists
idx_audit_user

on public.audit_logs(user_id);


create index if not exists
idx_audit_created

on public.audit_logs(created_at desc);


/* =====================================================
   4. ENABLE RLS
   ===================================================== */

alter table public.profiles
enable row level security;


alter table public.audit_logs
enable row level security;


/* =====================================================
   5. ADMIN CHECK FUNCTION
   ===================================================== */

create or replace function
public.is_admin()

returns boolean

language sql

stable

security definer

set search_path = public

as $$

    select exists (

        select 1

        from public.profiles

        where id = auth.uid()

        and role = 'admin'

        and active = true

    );

$$;


/* =====================================================
   6. PROFILE — USER READ OWN PROFILE
   ===================================================== */

drop policy if exists
profiles_self_read
on public.profiles;


create policy
profiles_self_read

on public.profiles

for select

to authenticated

using (

    id = auth.uid()

);


/* =====================================================
   7. PROFILE — ADMIN FULL ACCESS
   ===================================================== */

drop policy if exists
profiles_admin_all
on public.profiles;


create policy
profiles_admin_all

on public.profiles

for all

to authenticated

using (

    public.is_admin()

)

with check (

    public.is_admin()

);


/* =====================================================
   8. AUDIT — USER INSERT OWN LOG
   ===================================================== */

drop policy if exists
audit_insert_self
on public.audit_logs;


create policy
audit_insert_self

on public.audit_logs

for insert

to authenticated

with check (

    user_id = auth.uid()

);


/* =====================================================
   9. AUDIT — ADMIN READ
   ===================================================== */

drop policy if exists
audit_admin_read
on public.audit_logs;


create policy
audit_admin_read

on public.audit_logs

for select

to authenticated

using (

    public.is_admin()

);


/* =====================================================
   10. AUDIT — ADMIN DELETE
   ===================================================== */

drop policy if exists
audit_admin_delete
on public.audit_logs;


create policy
audit_admin_delete

on public.audit_logs

for delete

to authenticated

using (

    public.is_admin()

);


/* =====================================================
   11. UPDATED_AT FUNCTION
   ===================================================== */

create or replace function
public.update_updated_at()

returns trigger

language plpgsql

as $$

begin

    new.updated_at = now();

    return new;

end;

$$;


/* =====================================================
   12. UPDATED_AT TRIGGER
   ===================================================== */

drop trigger if exists
profiles_updated_at

on public.profiles;


create trigger
profiles_updated_at

before update

on public.profiles

for each row

execute function
public.update_updated_at();


/* =====================================================
   13. CHECK CURRENT USER FUNCTION
   ===================================================== */

create or replace function
public.get_my_profile()

returns json

language sql

stable

security definer

set search_path = public

as $$

    select row_to_json(p)

    from (

        select

            id,

            username,

            display_name,

            role,

            active,

            created_at,

            updated_at

        from public.profiles

        where id = auth.uid()

        limit 1

    ) p;

$$;


/* =====================================================
   14. GRANT FUNCTION ACCESS
   ===================================================== */

grant execute

on function
public.get_my_profile()

to authenticated;


grant execute

on function
public.is_admin()

to authenticated;


/* =====================================================
   15. CREATE FIRST ADMIN
   =====================================================

   สำคัญ:

   ยังไม่ต้องรันส่วนนี้ทันที

   หลังจากสร้าง User ใน
   Supabase Authentication แล้ว
   ให้นำ UUID ของ User มาใส่แทน

   YOUR_AUTH_USER_UUID

===================================================== */


/*

insert into public.profiles
(
    id,
    username,
    display_name,
    role,
    active
)

values
(
    'YOUR_AUTH_USER_UUID',
    'sakkranon',
    'ผู้ใหญ่บ้าน',
    'admin',
    true
)

on conflict (id)

do update set

    username =
        excluded.username,

    display_name =
        excluded.display_name,

    role =
        'admin',

    active =
        true,

    updated_at =
        now();

*/


/* =====================================================
   16. ตรวจสอบว่า ADMIN มีอยู่หรือไม่
   ===================================================== */

/*

select

    id,

    username,

    display_name,

    role,

    active,

    created_at

from public.profiles

order by created_at desc;

*/


/* =====================================================
   17. ตรวจสอบ AUDIT LOG
   ===================================================== */

/*

select

    id,

    username,

    action,

    target,

    details,

    created_at

from public.audit_logs

order by created_at desc

limit 50;

*/


/* =====================================================
   END
   ===================================================== */
