CREATE TABLE IF NOT EXISTS complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tracking_code TEXT UNIQUE,          -- รหัสติดตามเรื่อง (เช่น CMP-2026-001)
  reporter_name TEXT NOT NULL,         -- ชื่อผู้แจ้ง
  reporter_phone TEXT,                -- เบอร์โทรศัพท์
  category TEXT NOT NULL,             -- หมวดหมู่ (เช่น สาธารณูปโภค, เสียงดัง, ขยะ)
  title TEXT NOT NULL,                -- หัวข้อเรื่องร้องเรียน
  details TEXT,                       -- รายละเอียด
  location TEXT,                      -- สถานที่เกิดเหตุ / พิกัด
  status TEXT DEFAULT 'pending',      -- สถานะ: pending, in_progress, completed, rejected
  admin_remark TEXT,                  -- หมายเหตุ/การตอบกลับจากผู้ใหญ่บ้าน
  image_url TEXT,                     -- รูปภาพประกอบที่ชาวบ้านแนบมา
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
