/* =========================================================
   RONGKHEM e-VILLAGE OFFICE
   DATABASE V1.0
   บ้านร่องเข็ม หมู่ที่ 6
   ต.จำป่าหวาย อ.เมืองพะเยา จ.พะเยา

   รวม:
   - Admin Profile
   - RLS
   - Audit Log
   - ประชาชน
   - ครัวเรือน
   - ผู้สูงอายุ
   - ผู้พิการ
   - กลุ่มเปราะบาง
   - ข่าวสาร
   - กิจกรรม
   - โครงการ
   - เรื่องร้องเรียน
   - ผู้นำชุมชน
   ========================================================= */


/* =========================================================
   1. PROFILES
   ========================================================= */

create table if not exists public.profiles (

    id uuid primary key
        references auth.users(id)
        on delete cascade,

    username text unique not null,

    display_name text
        default 'ผู้ใหญ่บ้าน',

    role text not null
        default 'admin',

    active boolean not null
        default true,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now(),

    constraint profiles_role_check
    check (
        role in (
            'admin',
            'leader',
            'staff',
            'viewer'
        )
    )
);


/* =========================================================
   2. AUDIT LOGS
   ========================================================= */

create table if not exists public.audit_logs (

    id bigint generated by default as identity
        primary key,

    user_id uuid
        references auth.users(id)
        on delete set null,

    username text,

    action text not null,

    target text,

    details jsonb
        default '{}'::jsonb,

    created_at timestamptz
        default now()
);


/* =========================================================
   3. LEADERS
   ========================================================= */

create table if not exists public.leaders (

    id bigint generated by default as identity
        primary key,

    name text not null,

    position text not null,

    village text
        default 'บ้านร่องเข็ม หมู่ที่ 6',

    phone text,

    image_url text,

    biography text,

    active boolean
        default true,

    sort_order integer
        default 0,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   4. HOUSEHOLDS
   ========================================================= */

create table if not exists public.households (

    id bigint generated by default as identity
        primary key,

    house_number text not null,

    moo text
        default '6',

    village text
        default 'บ้านร่องเข็ม',

    head_name text,

    phone text,

    address_detail text,

    latitude numeric,

    longitude numeric,

    active boolean
        default true,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   5. CITIZENS
   ========================================================= */

create table if not exists public.citizens (

    id bigint generated by default as identity
        primary key,

    household_id bigint
        references public.households(id)
        on delete set null,

    citizen_code text unique,

    prefix text,

    first_name text not null,

    last_name text,

    gender text,

    birth_date date,

    phone text,

    occupation text,

    status text
        default 'ปกติ',

    active boolean
        default true,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   6. ELDERLY
========================================================= */

create table if not exists public.elderly (

    id bigint generated by default as identity
        primary key,

    citizen_id bigint
        references public.citizens(id)
        on delete cascade,

    age integer,

    pension_status text,

    care_level text,

    notes text,

    active boolean
        default true,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   7. DISABLED
========================================================= */

create table if not exists public.disabled_persons (

    id bigint generated by default as identity
        primary key,

    citizen_id bigint
        references public.citizens(id)
        on delete cascade,

    disability_type text,

    disability_card boolean
        default false,

    support_needed text,

    notes text,

    active boolean
        default true,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   8. VULNERABLE GROUP
========================================================= */

create table if not exists public.vulnerable_groups (

    id bigint generated by default as identity
        primary key,

    citizen_id bigint
        references public.citizens(id)
        on delete cascade,

    category text,

    description text,

    support_needed text,

    priority text
        default 'ปกติ',

    active boolean
        default true,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   9. NEWS
========================================================= */

create table if not exists public.news (

    id bigint generated by default as identity
        primary key,

    title text not null,

    content text,

    category text
        default 'ประชาสัมพันธ์',

    image_url text,

    published boolean
        default true,

    published_at timestamptz
        default now(),

    created_by uuid
        references auth.users(id)
        on delete set null,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   10. ACTIVITIES
========================================================= */

create table if not exists public.activities (

    id bigint generated by default as identity
        primary key,

    title text not null,

    description text,

    activity_date date,

    location text,

    participants integer
        default 0,

    image_url text,

    created_by uuid
        references auth.users(id)
        on delete set null,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   11. PROJECTS
========================================================= */

create table if not exists public.projects (

    id bigint generated by default as identity
        primary key,

    title text not null,

    description text,

    budget numeric
        default 0,

    status text
        default 'กำลังดำเนินการ',

    start_date date,

    end_date date,

    image_url text,

    created_by uuid
        references auth.users(id)
        on delete set null,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   12. COMPLAINTS
========================================================= */

create table if not exists public.complaints (

    id bigint generated by default as identity
        primary key,

    title text not null,

    detail text not null,

    reporter_name text,

    reporter_phone text,

    status text
        default 'รับเรื่อง',

    priority text
        default 'ปกติ',

    assigned_to uuid
        references auth.users(id)
        on delete set null,

    response text,

    created_at timestamptz
        default now(),

    updated_at timestamptz
        default now()
);


/* =========================================================
   13. INDEX
   ========================================================= */

create index if not exists
idx_citizens_household
on public.citizens(household_id);

create index if not exists
idx_citizens_name
on public.citizens(first_name,last_name);

create index if not exists
idx_elderly_citizen
on public.elderly(citizen_id);

create index if not exists
idx_disabled_citizen
on public.disabled_persons(citizen_id);

create index if not exists
idx_vulnerable_citizen
on public.vulnerable_groups(citizen_id);

create index if not exists
idx_news_date
on public.news(published_at desc);

create index if not exists
idx_activity_date
on public.activities(activity_date desc);

create index if not exists
idx_project_date
on public.projects(start_date desc);

create index if not exists
idx_complaints_status
on public.complaints(status);

create index if not exists
idx_audit_date
on public.audit_logs(created_at desc);


/* =========================================================
   14. ENABLE RLS
   ========================================================= */

alter table public.profiles enable row level security;

alter table public.audit_logs enable row level security;

alter table public.leaders enable row level security;

alter table public.households enable row level security;

alter table public.citizens enable row level security;

alter table public.elderly enable row level security;

alter table public.disabled_persons enable row level security;

alter table public.vulnerable_groups enable row level security;

alter table public.news enable row level security;

alter table public.activities enable row level security;

alter table public.projects enable row level security;

alter table public.complaints enable row level security;


/* =========================================================
   15. ADMIN FUNCTION
   ========================================================= */

create or replace function public.is_admin()

returns boolean

language sql

stable

security definer

set search_path = public

as $$

    select exists (

        select 1

        from public.profiles

        where id = auth.uid()

        and role = 'admin'

        and active = true

    );

$$;


/* =========================================================
   16. PROFILE POLICIES
   ========================================================= */

drop policy if exists
profiles_self_read
on public.profiles;

create policy
profiles_self_read

on public.profiles

for select

to authenticated

using (
    id = auth.uid()
);


drop policy if exists
profiles_admin_all
on public.profiles;

create policy
profiles_admin_all

on public.profiles

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


/* =========================================================
   17. ADMIN CRUD POLICIES
   ========================================================= */

drop policy if exists leaders_admin_all
on public.leaders;

create policy leaders_admin_all

on public.leaders

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists households_admin_all
on public.households;

create policy households_admin_all

on public.households

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists citizens_admin_all
on public.citizens;

create policy citizens_admin_all

on public.citizens

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists elderly_admin_all
on public.elderly;

create policy elderly_admin_all

on public.elderly

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists disabled_admin_all
on public.disabled_persons;

create policy disabled_admin_all

on public.disabled_persons

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists vulnerable_admin_all
on public.vulnerable_groups;

create policy vulnerable_admin_all

on public.vulnerable_groups

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists news_admin_all
on public.news;

create policy news_admin_all

on public.news

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists activities_admin_all
on public.activities;

create policy activities_admin_all

on public.activities

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists projects_admin_all
on public.projects;

create policy projects_admin_all

on public.projects

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


drop policy if exists complaints_admin_all
on public.complaints;

create policy complaints_admin_all

on public.complaints

for all

to authenticated

using (
    public.is_admin()
)

with check (
    public.is_admin()
);


/* =========================================================
   18. PUBLIC READ-ONLY DATA
   =========================================================

   ประชาชนเห็นได้เฉพาะข้อมูลที่ตั้งใจเปิดเผย
   ไม่เปิด citizens / households / elderly ฯลฯ
   ========================================================= */

drop policy if exists
news_public_read
on public.news;

create policy
news_public_read

on public.news

for select

to anon,
authenticated

using (
    published = true
);


drop policy if exists
activities_public_read
on public.activities;

create policy
activities_public_read

on public.activities

for select

to anon,
authenticated

using (
    true
);


drop policy if exists
projects_public_read
on public.projects;

create policy
projects_public_read

on public.projects

for select

to anon,
authenticated

using (
    true
);


drop policy if exists
leaders_public_read
on public.leaders;

create policy
leaders_public_read

on public.leaders

for select

to anon,
authenticated

using (
    active = true
);


/* =========================================================
   19. COMPLAINT PUBLIC INSERT
   ========================================================= */

drop policy if exists
complaints_public_insert
on public.complaints;

create policy
complaints_public_insert

on public.complaints

for insert

to anon,
authenticated

with check (
    true
);


/* =========================================================
   20. AUDIT LOG
   ========================================================= */

drop policy if exists
audit_insert_self
on public.audit_logs;

create policy
audit_insert_self

on public.audit_logs

for insert

to authenticated

with check (
    user_id = auth.uid()
);


drop policy if exists
audit_admin_read
on public.audit_logs;

create policy
audit_admin_read

on public.audit_logs

for select

to authenticated

using (
    public.is_admin()
);


drop policy if exists
audit_admin_delete
on public.audit_logs;

create policy
audit_admin_delete

on public.audit_logs

for delete

to authenticated

using (
    public.is_admin()
);


/* =========================================================
   21. UPDATED AT
   ========================================================= */

create or replace function
public.update_updated_at()

returns trigger

language plpgsql

as $$

begin

    new.updated_at = now();

    return new;

end;

$$;


/* =========================================================
   22. TRIGGERS
   ========================================================= */

drop trigger if exists
profiles_updated_at
on public.profiles;

create trigger
profiles_updated_at

before update
on public.profiles

for each row
execute function
public.update_updated_at();


drop trigger if exists
households_updated_at
on public.households;

create trigger
households_updated_at

before update
on public.households

for each row
execute function
public.update_updated_at();


drop trigger if exists
citizens_updated_at
on public.citizens;

create trigger
citizens_updated_at

before update
on public.citizens

for each row
execute function
public.update_updated_at();


drop trigger if exists
news_updated_at
on public.news;

create trigger
news_updated_at

before update
on public.news

for each row
execute function
public.update_updated_at();


drop trigger if exists
activities_updated_at
on public.activities;

create trigger
activities_updated_at

before update
on public.activities

for each row
execute function
public.update_updated_at();


drop trigger if exists
projects_updated_at
on public.projects;

create trigger
projects_updated_at

before update
on public.projects

for each row
execute function
public.update_updated_at();


drop trigger if exists
complaints_updated_at
on public.complaints;

create trigger
complaints_updated_at

before update
on public.complaints

for each row
execute function
public.update_updated_at();


/* =========================================================
   23. DASHBOARD STATISTICS
   ========================================================= */

create or replace function
public.dashboard_stats()

returns json

language sql

stable

security definer

set search_path = public

as $$

    select json_build_object(

        'population',
        (
            select count(*)
            from public.citizens
            where active = true
        ),

        'households',
        (
            select count(*)
            from public.households
            where active = true
        ),

        'elderly',
        (
            select count(*)
            from public.elderly
            where active = true
        ),

        'disabled',
        (
            select count(*)
            from public.disabled_persons
            where active = true
        ),

        'vulnerable',
        (
            select count(*)
            from public.vulnerable_groups
            where active = true
        ),

        'activities',
        (
            select count(*)
            from public.activities
        ),

        'projects',
        (
            select count(*)
            from public.projects
        ),

        'complaints',
        (
            select count(*)
            from public.complaints
        )

    );

$$;


/* =========================================================
   24. DASHBOARD FUNCTION PERMISSION
   ========================================================= */

grant execute
on function public.dashboard_stats()
to anon,
authenticated;


/* =========================================================
   25. CREATE DEFAULT LEADERS
   ========================================================= */

insert into public.leaders
(
    name,
    position,
    village,
    sort_order
)

select
    'นายศักรนนทน์ ขัติย์วงศ์',
    'ผู้ใหญ่บ้าน',
    'บ้านร่องเข็ม หมู่ที่ 6',
    1

where not exists (

    select 1

    from public.leaders

    where name =
        'นายศักรนนทน์ ขัติย์วงศ์'

);


/* =========================================================
   26. TEST DASHBOARD
   ========================================================= */

select
    public.dashboard_stats();


/* =========================================================
   27. CHECK TABLES
   ========================================================= */

select
    table_name

from information_schema.tables

where table_schema = 'public'

order by table_name;


/* =========================================================
   END
   ========================================================= */
